In [16]:
import numpy as np

In [17]:
input_value = np.array([[0,0] , [0,1] , [1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

# assigning output values

In [18]:
output = np.array([0,1,1,0])
output = output.reshape(4,1)
output.shape

(4, 1)

# weights

In [19]:
weights = np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [20]:
bias = 0.3

# activation function

In [21]:
def sigmoid_func(x):
    return 1/(1+np.exp(-x))

In [26]:
def der(x):
    return sigmoid_func(x) * (1- sigmoid_func(x))

# update the weights

In [11]:
pp=np.dot(input_arr,weights)

In [12]:
pp

array([[0. ],
       [0.2],
       [0.3],
       [0.1]])

In [13]:
p1=pp+bias

In [14]:
p1

array([[0.3],
       [0.5],
       [0.6],
       [0.4]])

In [23]:
weighted_sum

array([[0.3],
       [0.5],
       [0.6],
       [0.4]])

In [24]:
sigmoid_func(weighted_sum)

array([[0.57444252],
       [0.62245933],
       [0.64565631],
       [0.59868766]])

In [25]:
error = first_output - output

In [27]:
for epochs in range(10000):
    input_arr = input_value
    dot = np.dot(input_arr,weights)
    weighted_sum = dot + bias
    first_output = sigmoid_func(weighted_sum)
    error = first_output - output
    total_error = np.square(np.subtract(first_output,output)).mean()
    first_der=error
    second_der = der(first_output)
    derivative = first_der * second_der
    t_input = input_value.T
    final_derivative = np.dot(t_input,derivative)
    weights = weights - 0.05 * final_derivative
    for i in derivative:
        bias = bias - 0.05 * i
    
print(weights)
print(bias)


[[-0.41953547]
 [ 8.98887811]]
[-4.19706344]


In [28]:
pred = np.array([0,1])
result = np.dot(pred,weights) + bias
res = sigmoid_func(result)
print(res)
    

[0.99177089]


In [29]:
first_output = sigmoid_func(weighted_sum)
print(first_output)

[[0.01481834]
 [0.99177007]
 [0.98753364]
 [0.00979057]]
